---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: portal-database-secret
  namespace: edc-dev
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgBypcz9PqRHvEKRQ889vKKTW6Fy7ZnhWJv9Un0IQ5GXjMGY8ubJq0jt2/b0ndAp7Iz8vQnG/wTlFv80xJg8HNgfO5Pd/GtQJnZk2+DelWDV//g2xLGFQ4Arg4adCxIcJcIem13BgEVP2medTQdzccWttmomJQEXXNFWXVkLej/JE32bPIOhnfto0U7kLsHq4BJcQ8l6kIUN29yLahPG1ZxU1DMCE7Nhhx9wbZ+qsCjwg/hPZNUp0zR12vY8Fmq5s7x3Gg3VCvh9WZkvERlJlf8Ctgcx8OtIYwa2bTClD3E3lYXXWw3oexaTFwYJXMXZ/g05CL2Tsmv9ufkaU9mfvvA9JwmOcFG3ZuO95d72mom9QRkKE5lrczf3QrCyXEszMT6EDrAcoJV+HjNct5qhYDJCQYcGovQhMUpiLSMNr8lr/nUKeuX3s7sFDhGJ6Z6ypbZwF0mlw1a7zE7EFpqh+ltT/Z84yJnmNxYaRtjtcEK8ZpzVRyUUDhOW5iSM3KKfXGD+S+FN/dNdgIXfH50qffzPPzz1D51+fTUqTZvqlIozdQUeBdkoykqzdQNOBlVk6KdTcHPmJmVJuRaucV/Jby44/YDLyhQF6eYsdT+Ae9pRzSsk99MkXRljB4AK9AFiE7QONMt/dzJelUSsV1QNnfCKv/YS1GGSG4g6jzB85OdFmwCeLM0to10ErFFBCi430dpg24mBknL4G2prPfi+EOwk
  template:
    metadata:
      creationTimestamp: null
      name: portal-database-secret
      namespace: edc-dev
    type: Opaque
