---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: provider-management-secrets
  namespace: edc-dev
spec:
  encryptedData:
    EDC_XAPIKEY: AgB9X5lPRMNbD1FQr49spWLOkos7hNVRrDy9Kofoo3x37T667hEf8aOcdL2WMyb0rOdulIF3EoZiHscCRe4fT1DrYVShFX/VmLTmRE1DVzpn3uRqTBKa81AlcOK5sFPUvLP7X4INCope9BCnrR72g502Ky2iR0TWv7KmvZX/pMT+qLFfs9BA5yjPs7S8PtdrBd42QALx8l+g6bcwZRPazvbMpaWo3862OAyqB32l/twuCWkOO98TxsrGx6Zh4a7CfUxhgTYCzVEkKt4R8kELM6O1jFPeO5rtNO4e9u1KgD4V2vFX32/VfH6ppxWgVoZZMao3PWA8nNL84CzyZZNsoKfs0aU7PiZNdQ6PbIcsBuCiFn4OJsjn1zAqx734FPmATCHN9c1Mb3/ctMOSr2DXEHrxzGx5mpQQC1a90Sgk7Ydc5V210/alOdg576dTH/75Ckw8I0X9s4Mu0jHfoEoPN3Z0n+rtqvObnmyNa9N3HdtrriUE/yR9Kiu92L3/DGfkS9H57wXO89ktbGuk2SvleiXXELKfoOjFPyey4JY6Q6jJakdkKWVYQCmpUIpqtmfFsKRp/e5SQh7ks+loGMGUXnlT3naGldFfKo3yKdUj0Muk8rzBDgK2umVS+qXYqxLR5y7iWoZRysJrtfjVrBXtiIPSxOkdCSutgpMwydnX2HdiCr0I728RUh/aVVQAR2j8keARihDtjTO7xA==
    FH_CATALOG_SECRETKEY: AgAMrXrANsHEGZfqIHaw41tjnCTjeIKLRKutQddI5MUqHZzdcELW3LiUI9PYht2YV6jl8wXUkzAbwKTxVrkLGgxAi2PdRsrfNjcnM+bpr8lpekZLfQ7VcGRMqi9H4TU6YRjZPa5EZeWS/ksqk13ISk+hPEIEMjeFYstDhn1BnKg8vqxEIRLmalejNTZ+uSJ1Up/AVA/EYZz/IpH2bTT4dBHi+94XHZQ29EG90QuV2x5odk1hfUYQaleHZuevdnziDD1r3XoXSo3coYl1NsFUN3QJ7lbheN6um8o18111o1ZC7iBO5IIhMMdSPJra2ISxVXNOP2D9rPILOkS9/E+Ol6ErpmyV+rBxVJdxz9tmpztgt65MSnYVedhxLltokM1VYXjR5rOwy8tYI2lVjB6dQ+dIQtZqhInVEtiaazkqJnkpcN+tczuussH7A/NF0z2ej6rSTM+epIPEu3eNCoRestV5engvfYhPkwJHUZgY4bRJLxMMD3WAoRTqMSUlWolUltBEpkpmRiKKQpWRESNNDToyhBwRjnJyVnGCUn6syKVwlvxwZ1G4jmoEA9VuyBA+RasG2BUJwdUYvyaaB+tFE3lDhfrp+Nl1JVpot44/AryhLWhBHS4oUu3htnfNaAtAYhzZOf+LJ6yolgdhXl92cDIwhKjaF3SkYxWFnJPaXrgwLc9/s3KDVI8eInqxe3gt7BgIwU9Pv7WSNSlrUczzVIlIeNTcFnCjjfhBGw08V/ZBd3hYx2ZfNt3HTUmjK4oFzwiMZgCtndmGx9Na97pr/tSF3H43xoXbY37uNKNTw6y4gxKC6yCwDkUZvK8wyoxQy0wpw3/Er3AV+cj5EPeL+BsMeagNqY7BHSP5nUvCx0euisqefqwU
  template:
    metadata:
      creationTimestamp: null
      name: provider-management-secrets
      namespace: edc-dev
    type: Opaque
